# Generated by Django 6.0.3 on 2026-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_skill_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Зарплата'),
        ),
    ]
