# Generated by Django 6.0.3 on 2026-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_vacancy_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='area_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID региона вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='area_name',
            field=models.CharField(default=0, max_length=255, verbose_name='Регион вакансии'),
            preserve_default=False,
        ),
    ]
