# Generated by Django 6.0.3 on 2026-04-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_vacancy_area_id_vacancy_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='area_name',
        ),
    ]
