# Generated by Django 6.0.3 on 2026-04-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_vacancy_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='data.uniqueuser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
