# Generated by Django 6.0.3 on 2026-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_profession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название профессии / запрос'),
        ),
    ]
