# Generated by Django 6.0.3 on 2026-04-14 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_profession_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={},
        ),
        migrations.RemoveField(
            model_name='profession',
            name='user',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='user_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='data.userprofessionrequest'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='area_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='data.profession'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(related_name='vacancies', to='data.skill'),
        ),
    ]
