# Generated by Django 6.0.4 on 2026-04-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_vacancy_options_remove_profession_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published_at'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='area_id',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='url',
            field=models.URLField(default=0, max_length=500, verbose_name='Ссылка на HH.ru'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата (средняя)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='user_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='data.userprofessionrequest'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.IntegerField(unique=True, verbose_name='ID на HH.ru')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data.area')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='areas',
            field=models.ManyToManyField(related_name='vacancies', to='data.area', verbose_name='Регионы'),
        ),
    ]
