# Generated by Django 6.0.4 on 2026-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_vacancy_options_remove_vacancy_area_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
    ]
